-- Synthetic local-only records. These values are deterministic and contain no
-- personal or production data.

insert into public.customer_enquiries (
  id,
  full_name,
  email,
  phone,
  contact_preference,
  consent_confirmed,
  consent_given_at,
  questionnaire_answers,
  source,
  status,
  created_at,
  updated_at
)
values (
  '00000000-0000-0000-0000-000000000001',
  'Local Test Buyer',
  'buyer@example.test',
  '+1 416 555 0100',
  'whatsapp',
  true,
  '2026-01-01T00:00:00Z',
  '{"formVersion":3,"q1":"personal-wellbeing","q2":"just-for-me","q3":["stress","sleep"],"q4":"planning-ahead","q5":"Synthetic local enquiry"}'::jsonb,
  'website',
  'new',
  '2026-01-01T00:00:00Z',
  '2026-01-01T00:00:00Z'
)
on conflict (id) do nothing;

-- The following records come from the supplied Solas Guide founding-cohort
-- profile pack. They remain drafts until each profile has been reviewed.
-- Portraits were not supplied in that pack, so image fields stay null.

insert into public.practitioner_terms (type, name, slug, sort_order)
values
  ('support_area', $term$Trauma & nervous system$term$, 'trauma-and-nervous-system', 10),
  ('support_area', $term$Anxiety & emotional wellbeing$term$, 'anxiety-and-emotional-wellbeing', 20),
  ('support_area', $term$Stress & burnout$term$, 'stress-and-burnout', 30),
  ('support_area', $term$Life transitions$term$, 'life-transitions', 40),
  ('support_area', $term$Leadership & work$term$, 'leadership-and-work', 50),
  ('support_area', $term$Relationships & intimacy$term$, 'relationships-and-intimacy', 60),
  ('support_area', $term$Purpose & personal growth$term$, 'purpose-and-personal-growth', 70),
  ('support_area', $term$Physical wellbeing$term$, 'physical-wellbeing', 80),
  ('support_area', $term$Women’s wellbeing$term$, 'womens-wellbeing', 90),
  ('support_area', $term$Grief & loss$term$, 'grief-and-loss', 100),
  ('support_area', $term$Spiritual practice & connection$term$, 'spiritual-practice-and-connection', 110),
  ('support_area', $term$Emotional wellbeing$term$, 'emotional-wellbeing', 120),
  ('support_area', $term$Men’s wellbeing$term$, 'mens-wellbeing', 130),
  ('support_area', $term$Family & parenting$term$, 'family-and-parenting', 140),
  ('support_area', $term$Sleep & rest$term$, 'sleep-and-rest', 150),

  ('approach', $term$Therapy & counselling$term$, 'therapy-and-counselling', 10),
  ('approach', $term$Somatic & body-based$term$, 'somatic-and-body-based', 20),
  ('approach', $term$Coaching$term$, 'coaching', 30),
  ('approach', $term$Meditation & mindfulness$term$, 'meditation-and-mindfulness', 40),
  ('approach', $term$Energy & sound$term$, 'energy-and-sound', 50),
  ('approach', $term$Traditional & spiritual practices$term$, 'traditional-and-spiritual-practices', 60),
  ('approach', $term$Yoga & movement$term$, 'yoga-and-movement', 70),
  ('approach', $term$Breathwork$term$, 'breathwork', 80),
  ('approach', $term$Bodywork & physical therapies$term$, 'bodywork-and-physical-therapies', 90),
  ('approach', $term$Experiential / developmental$term$, 'experiential-developmental', 100),
  ('approach', $term$Nutrition & lifestyle$term$, 'nutrition-and-lifestyle', 110),
  ('approach', $term$Coaching / guided practice$term$, 'coaching-guided-practice', 120),
  ('approach', $term$Sleep & dreamwork$term$, 'sleep-and-dreamwork', 130),

  ('modality', $term$Integrative hypnotherapy$term$, 'integrative-hypnotherapy', 10),
  ('modality', $term$Holistic Hypnotherapy$term$, 'holistic-hypnotherapy', 15),
  ('modality', $term$Subconscious pattern work$term$, 'subconscious-pattern-work', 20),
  ('modality', $term$Trauma-informed practice$term$, 'trauma-informed-practice', 30),
  ('modality', $term$Strategy advisory$term$, 'strategy-advisory', 40),
  ('modality', $term$Mentoring$term$, 'mentoring', 50),
  ('modality', $term$Leadership and organisational transformation$term$, 'leadership-and-organisational-transformation', 60),
  ('modality', $term$NLP-informed work$term$, 'nlp-informed-work', 70),
  ('modality', $term$Subconscious mastery coaching$term$, 'subconscious-mastery-coaching', 80),
  ('modality', $term$Hypnotherapy / RTT$term$, 'hypnotherapy-rtt', 90),
  ('modality', $term$Hypnotherapy$term$, 'hypnotherapy', 95),
  ('modality', $term$Narrative Coaching$term$, 'narrative-coaching', 100),
  ('modality', $term$Conversational Intelligence$term$, 'conversational-intelligence', 110),
  ('modality', $term$Somatics & embodiment$term$, 'somatics-and-embodiment', 120),
  ('modality', $term$Usui Reiki$term$, 'usui-reiki', 130),
  ('modality', $term$Karuna Reiki$term$, 'karuna-reiki', 140),
  ('modality', $term$Kirtan$term$, 'kirtan', 150),
  ('modality', $term$Meditation$term$, 'meditation', 160),
  ('modality', $term$Sound healing$term$, 'sound-healing', 170),
  ('modality', $term$Shiatsu Anma$term$, 'shiatsu-anma', 180),
  ('modality', $term$Pranic healing$term$, 'pranic-healing', 190),
  ('modality', $term$Crystal therapy$term$, 'crystal-therapy', 200),
  ('modality', $term$Chakra work$term$, 'chakra-work', 210),
  ('modality', $term$Vinyasa Yoga$term$, 'vinyasa-yoga', 220),
  ('modality', $term$Restorative Yoga$term$, 'restorative-yoga', 230),
  ('modality', $term$Pranayama$term$, 'pranayama', 240),
  ('modality', $term$Trauma-Informed Yoga$term$, 'trauma-informed-yoga', 250),
  ('modality', $term$Reiki$term$, 'reiki', 260),
  ('modality', $term$Teacher mentoring$term$, 'teacher-mentoring', 270),
  ('modality', $term$Somatic trauma work$term$, 'somatic-trauma-work', 280),
  ('modality', $term$Somatic Trauma Release Breathwork$term$, 'somatic-trauma-release-breathwork', 290),
  ('modality', $term$Biodynamic Trauma Release Breathwork$term$, 'biodynamic-trauma-release-breathwork', 300),
  ('modality', $term$Myofascial Release$term$, 'myofascial-release', 310),
  ('modality', $term$Dynamic Spiral Yin Fascial Yoga$term$, 'dynamic-spiral-yin-fascial-yoga', 320),
  ('modality', $term$Family Constellation$term$, 'family-constellation', 330),
  ('modality', $term$Breathwork$term$, 'breathwork', 340),
  ('modality', $term$Cold exposure$term$, 'cold-exposure', 350),
  ('modality', $term$TRE$term$, 'tre', 360),
  ('modality', $term$Body-oriented practice$term$, 'body-oriented-practice', 370),
  ('modality', $term$Systemic work$term$, 'systemic-work', 380),
  ('modality', $term$Prenatal Yoga$term$, 'prenatal-yoga', 390),
  ('modality', $term$Aquatic bodywork$term$, 'aquatic-bodywork', 400),
  ('modality', $term$ISHTA Yoga$term$, 'ishta-yoga', 410),
  ('modality', $term$Yin Yoga$term$, 'yin-yoga', 420),
  ('modality', $term$Integrative wellbeing$term$, 'integrative-wellbeing', 430),
  ('modality', $term$Longevity$term$, 'longevity', 440),
  ('modality', $term$Humanistic Gestalt Counselling$term$, 'humanistic-gestalt-counselling', 450),
  ('modality', $term$Integrated counselling$term$, 'integrated-counselling', 460),
  ('modality', $term$Humanistic coaching$term$, 'humanistic-coaching', 470),
  ('modality', $term$Breathing Cold method$term$, 'breathing-cold-method', 480),
  ('modality', $term$Ice bath facilitation$term$, 'ice-bath-facilitation', 490),
  ('modality', $term$Yoga Energetics$term$, 'yoga-energetics', 500),
  ('modality', $term$Craniosacral work$term$, 'craniosacral-work', 510),
  ('modality', $term$Energy healing$term$, 'energy-healing', 520),
  ('modality', $term$Somatic practice$term$, 'somatic-practice', 530),
  ('modality', $term$Shamanic / spiritual traditions$term$, 'shamanic-spiritual-traditions', 540),
  ('modality', $term$Women’s hormone health$term$, 'womens-hormone-health', 550),
  ('modality', $term$Functional nutrition$term$, 'functional-nutrition', 560),
  ('modality', $term$Perimenopause support$term$, 'perimenopause-support', 570),
  ('modality', $term$Lifestyle coaching$term$, 'lifestyle-coaching', 580),
  ('modality', $term$Melukat / Balinese water purification$term$, 'melukat-balinese-water-purification', 590),
  ('modality', $term$Prayer$term$, 'prayer', 600),
  ('modality', $term$Mantra$term$, 'mantra', 610),
  ('modality', $term$Balinese Hindu spiritual practice$term$, 'balinese-hindu-spiritual-practice', 620),
  ('modality', $term$Pilates$term$, 'pilates', 630),
  ('modality', $term$GYROTONIC®$term$, 'gyrotonic', 640),
  ('modality', $term$Rolfing® Structural Integration$term$, 'rolfing-structural-integration', 650),
  ('modality', $term$Functional anatomy$term$, 'functional-anatomy', 660),
  ('modality', $term$Post-rehabilitation movement$term$, 'post-rehabilitation-movement', 670),
  ('modality', $term$Osteopathy$term$, 'osteopathy', 680),
  ('modality', $term$Pilates rehabilitation$term$, 'pilates-rehabilitation', 690),
  ('modality', $term$Craniosacral Osteopathy$term$, 'craniosacral-osteopathy', 700),
  ('modality', $term$Dry needling$term$, 'dry-needling', 710),
  ('modality', $term$Garuda$term$, 'garuda', 720),
  ('modality', $term$Zen Thai Shiatsu$term$, 'zen-thai-shiatsu', 730),
  ('modality', $term$Young men’s mentorship$term$, 'young-mens-mentorship', 740),
  ('modality', $term$Rites of passage$term$, 'rites-of-passage', 750),
  ('modality', $term$Youth development$term$, 'youth-development', 760),
  ('modality', $term$Group facilitation$term$, 'group-facilitation', 770),
  ('modality', $term$Outdoor challenge$term$, 'outdoor-challenge', 780),
  ('modality', $term$Sleep wellness$term$, 'sleep-wellness', 790),
  ('modality', $term$Dreamwork$term$, 'dreamwork', 800),
  ('modality', $term$Conscious dreaming$term$, 'conscious-dreaming', 810),
  ('modality', $term$Guided meditation$term$, 'guided-meditation', 820),
  ('modality', $term$Sleep and dream workshops$term$, 'sleep-and-dream-workshops', 830),
  ('modality', $term$Craniosacral therapy$term$, 'craniosacral-therapy', 840),
  ('modality', $term$Spiritual coaching$term$, 'spiritual-coaching', 850),
  ('modality', $term$Ayurveda$term$, 'ayurveda', 860),

  ('works_with', $term$Individuals$term$, 'individuals', 10),
  ('works_with', $term$Leaders & professional teams$term$, 'leaders-and-professional-teams', 20),
  ('works_with', $term$Groups$term$, 'groups', 30),
  ('works_with', $term$Couples$term$, 'couples', 40),
  ('works_with', $term$Children & teenagers$term$, 'children-and-teenagers', 50),

  ('location', $term$Bali$term$, 'bali', 10),
  ('location', $term$International$term$, 'international', 20),
  ('location', $term$Switzerland$term$, 'switzerland', 30),
  ('location', $term$Netherlands$term$, 'netherlands', 40),
  ('location', $term$Italy$term$, 'italy', 50),
  ('location', $term$Indonesia$term$, 'indonesia', 60),
  ('location', $term$Singapore$term$, 'singapore', 70),
  ('location', $term$Portugal$term$, 'portugal', 80),
  ('location', $term$Kenya$term$, 'kenya', 90),
  ('location', $term$UK$term$, 'uk', 100),

  ('language', $term$English$term$, 'english', 10)
on conflict (type, slug) do nothing;

insert into public.practitioners (
  id, slug, name, descriptor, years_active, summary, about, credentials,
  significant_training, offers_in_person, offers_online, website_url,
  instagram_url, image_path, image_alt, status, published_at
)
values
  (
    '00000000-0000-0000-0000-000000001001',
    'kartika-alexandra',
    $profile$Kartika Alexandra$profile$,
    $profile$Subconscious Mind & Trauma Specialist · Integrative Hypnotherapist$profile$,
    10,
    $profile$Works with subconscious patterns, trauma and nervous-system regulation to support lasting change in wellbeing, relationships and performance.$profile$,
    $profile$Kartika Alexandra is an Indonesian-Canadian integrative hypnotherapist, subconscious mind specialist and trauma-informed practitioner. Her work focuses on identifying and resolving subconscious patterns that can shape wellbeing, relationships and performance. She works internationally with founders, executives, leaders and other high-performing individuals, and is the founder of Maja Healing and HHHypnosis®.$profile$,
    array[$profile$BA Psychology, University of British Columbia$profile$, $profile$Founder, Maja Healing$profile$, $profile$Founder, HHHypnosis®$profile$],
    null, true, true, $profile$https://www.kartikaalexandra.com/$profile$, $profile$https://www.instagram.com/kartikaalexandra/$profile$, null, null, 'draft', null
  ),
  (
    '00000000-0000-0000-0000-000000001002',
    'sandra-echemendia',
    $profile$Sandra Echemendia$profile$,
    $profile$Strategy Advisor · Mentor · Entrepreneur$profile$,
    20,
    $profile$Supports entrepreneurs and organisations through growth, change and transformation with greater clarity, structure and alignment.$profile$,
    $profile$Sandra Echemendia is a strategy advisor, mentor and entrepreneur whose work focuses on helping people and organisations navigate growth, change and transformation. Her background spans business strategy, leadership, organisational development and personal development, bringing a practical and systems-oriented perspective to individual and professional change.$profile$,
    array[$profile$20+ years in strategy, leadership, organisational development and entrepreneurship$profile$],
    null, true, true, null, $profile$https://www.instagram.com/sandra.echemendia_en/$profile$, null, null, 'draft', null
  ),
  (
    '00000000-0000-0000-0000-000000001003',
    'helena-day',
    $profile$Helena Day$profile$,
    $profile$Subconscious Mastery Coach · Hypnotherapist$profile$,
    10,
    $profile$Helps founders and leaders shift persistent subconscious patterns affecting confidence, leadership, relationships and personal freedom.$profile$,
    $profile$Helena Day is a subconscious mastery coach and hypnotherapist. She works with founders, senior leaders and high-functioning professionals on patterns that can remain unchanged despite insight or conventional personal development work. Her approach combines coaching, subconscious pattern work, nervous-system awareness and embodiment.$profile$,
    array[$profile$10+ years working with founders, senior leaders and high-functioning professionals$profile$],
    null, true, true, $profile$https://www.helenaday.com/$profile$, $profile$https://www.instagram.com/helenaroseday/$profile$, null, null, 'draft', null
  ),
  (
    '00000000-0000-0000-0000-000000001004',
    'punnu-singh-wasu',
    $profile$Punnu Singh Wasu$profile$,
    $profile$Reiki · Meditation · Kirtan · Sound Healing$profile$,
    30,
    $profile$A long-standing meditation and healing practitioner working through Reiki, devotional music, sound and contemplative practice.$profile$,
    $profile$Punnu Singh Wasu is an Indian-born meditation teacher, musician and healing practitioner whose work spans Reiki, devotional music, sound and contemplative practice. He has taught in Bali for many years through private sessions, workshops, trainings and group experiences, and is known for bringing together devotional and energetic traditions in an accessible way.$profile$,
    array[$profile$Senior meditation teacher$profile$, $profile$30+ years of Reiki practice$profile$, $profile$Long-standing Yoga Barn faculty$profile$],
    null, true, true, $profile$https://www.punnuwasu.com/$profile$, $profile$https://www.instagram.com/punnuwasu/$profile$, null, null, 'draft', null
  ),
  (
    '00000000-0000-0000-0000-000000001005',
    'kimberley-utama',
    $profile$Kimberley Utama$profile$,
    $profile$Vinyasa Yoga · Self-Enquiry · Teacher Development$profile$,
    null,
    $profile$A yoga educator and mentor combining Vinyasa, self-enquiry, nervous-system awareness and counselling-informed teacher development.$profile$,
    $profile$Kimberley Utama is a Bali-based yoga educator and mentor. Her work combines Vinyasa, restorative yoga, meditation, pranayama, trauma-informed teaching and self-enquiry, with a strong focus on teacher development. She is a lead and master teacher on yoga teacher trainings and incorporates her counselling background into mentoring yoga teachers and graduates.$profile$,
    array[$profile$E-RYT 500$profile$, $profile$YACEP$profile$, $profile$Lead / master teacher on 200hr and 300hr yoga teacher trainings$profile$],
    null, true, true, $profile$https://www.kimberleyutama.yoga/$profile$, $profile$https://www.instagram.com/kimberleyutamayoga/$profile$, null, null, 'draft', null
  ),
  (
    '00000000-0000-0000-0000-000000001006',
    'beta-gaiana-lisboa',
    $profile$Beta Gaiana Lisboa$profile$,
    $profile$Somatic Experiencing · Trauma Release Breathwork · Somatic Embodiment$profile$,
    25,
    $profile$Supports women through somatic trauma healing, breathwork, embodiment and nervous-system regulation.$profile$,
    $profile$Beta Gaiana Lisboa is a somatic practitioner and educator whose work centres on trauma healing, nervous-system regulation, breathwork, fascia and women’s embodiment. She has worked with thousands of women across more than 25 years and teaches through private sessions, mentorships, retreats, trainings and somatic immersions.$profile$,
    array[$profile$Bachelor in Physical Education$profile$, $profile$MS Sports & Exercise Science$profile$, $profile$25+ years' practice$profile$],
    null, true, true, $profile$https://betalisboa.com/$profile$, $profile$https://www.instagram.com/somatic_trauma_healing/$profile$, null, null, 'draft', null
  ),
  (
    '00000000-0000-0000-0000-000000001007',
    'clare-hampton',
    $profile$Clare Hampton$profile$,
    $profile$Reiki · Holistic Hypnotherapy · Trauma-Informed Practice$profile$,
    null,
    $profile$Combines traditional Usui Reiki and holistic hypnotherapy to support deeper emotional patterns, self-discovery and change.$profile$,
    $profile$Clare Hampton is a Reiki practitioner and holistic hypnotherapist and the founder of The Inner Healing Rooms. Her work combines traditional Usui Reiki with hypnotherapy, supporting people to explore deeper emotional patterns, release what may be holding them back and reconnect with a clearer sense of self and direction.$profile$,
    array[$profile$Founder, The Inner Healing Rooms$profile$],
    null, true, true, $profile$https://www.theinnerhealingrooms.com/$profile$, $profile$https://www.instagram.com/theinnerhealingrooms/$profile$, null, null, 'draft', null
  ),
  (
    '00000000-0000-0000-0000-000000001008',
    'dirk-hamelijnck',
    $profile$Dirk Hamelijnck$profile$,
    $profile$Breathwork · Cold Exposure · TRE$profile$,
    10,
    $profile$Uses breath, cold exposure and body-oriented practice to support physical, emotional and nervous-system resilience.$profile$,
    $profile$Dirk Hamelijnck works with breath as a central tool in a body-oriented approach to physical and emotional development. His practice brings together breathwork, cold exposure, TRE, systemic awareness and body-based work, and he also teaches and trains facilitators in breath-led practice.$profile$,
    array[$profile$Approx. 10 years in breath and cold-exposure work$profile$],
    null, true, true, $profile$https://www.metdirk.nl/$profile$, $profile$https://www.instagram.com/dirkhamelijnck/$profile$, null, null, 'draft', null
  ),
  (
    '00000000-0000-0000-0000-000000001009',
    'indri-hapsari',
    $profile$Indri Hapsari$profile$,
    $profile$Breathwork · Reiki · Prenatal Yoga · Aquatic Bodywork$profile$,
    null,
    $profile$Works with breath and body-based practices to support regulation, recovery, transition and deeper self-connection.$profile$,
    $profile$Indri Hapsari is an Indonesian breathwork and body-based practitioner. Her work spans breathwork, Reiki, prenatal yoga and aquatic bodywork, with experience supporting people through stress, anxiety, addiction recovery and major life transitions. She has trained and practised in Bali for many years.$profile$,
    null,
    array[$profile$10-month breathwork facilitator training (2017–18)$profile$, $profile$Reiki Levels 1 & 2, Asian Healing Arts Center (2018)$profile$, $profile$Prenatal Yoga training (2018)$profile$],
    true, true, null, $profile$https://www.instagram.com/indrihapsari___/$profile$, null, null, 'draft', null
  ),
  (
    '00000000-0000-0000-0000-000000001010',
    'rajiv-arapurakal',
    $profile$Rajiv Arapurakal$profile$,
    $profile$Integrative Wellbeing · Yoga · Physician by Training$profile$,
    null,
    $profile$Brings together a medical background, senior yoga teaching and leadership experience in an integrative approach to wellbeing and reinvention.$profile$,
    $profile$Rajiv Arapurakal is a physician by training, senior yoga teacher and strategy leader. His work brings together a decade of experience in internal medicine with extensive yoga teaching and an interest in leadership, longevity, reinvention and human-centred transformation. Within Solas, his profile should present medicine as part of his professional background rather than imply current clinical medical practice unless separately confirmed.$profile$,
    array[$profile$MD$profile$, $profile$Internal Medicine training$profile$, $profile$10-year medical career$profile$, $profile$3,000+ yoga classes$profile$],
    null, true, true, null, $profile$https://www.instagram.com/rajiv_arapurakal/$profile$, null, null, 'draft', null
  ),
  (
    '00000000-0000-0000-0000-000000001011',
    'claudia-pietrantoni',
    $profile$Claudia Pietrantoni$profile$,
    $profile$Humanistic Gestalt Counselling · Couples · Adolescents$profile$,
    null,
    $profile$A professional counsellor working with relationships, anxiety, identity, loss, change and personal or professional development.$profile$,
    $profile$Claudia Pietrantoni is a professional counsellor, coach and facilitator whose work spans individuals, couples, adolescents and organisational contexts. She supports people working with anxiety, overwhelm, relationships, identity, loss and change, and also brings extensive experience in leadership, human resources and organisational development.$profile$,
    array[$profile$Professional Advanced Counselor, AssoCounseling REG-A0732-2012$profile$],
    null, true, true, $profile$https://www.claudiapi.com/$profile$, $profile$https://www.instagram.com/claudiapi/$profile$, null, null, 'draft', null
  ),
  (
    '00000000-0000-0000-0000-000000001012',
    'alexandre-tsuk',
    $profile$Alexandre Tsuk$profile$,
    $profile$Breathwork · Cold Exposure · Facilitator Training$profile$,
    10,
    $profile$Founder of Breathing Cold, combining breathwork and cold exposure through individual, group and facilitator-training experiences.$profile$,
    $profile$Alexandre Tsuk is the founder of Breathing Cold, a Bali-based method combining breathwork and cold exposure. His work includes individual and group experiences as well as facilitator training, with Breathing Cold publicly reporting more than 7,000 people guided and almost 600 facilitators trained.$profile$,
    array[$profile$Founder, Breathing Cold$profile$, $profile$10+ years in the work$profile$, $profile$Breathing Cold publicly reports 7,000+ people guided and nearly 600 facilitators trained$profile$],
    null, true, true, $profile$https://breathingcoldbali.com/$profile$, $profile$https://www.instagram.com/breathingcoldbali/$profile$, null, null, 'draft', null
  ),
  (
    '00000000-0000-0000-0000-000000001013',
    'cat-kabira',
    $profile$Cat Kabira$profile$,
    $profile$Yoga Energetics · Craniosacral · Energy Healing$profile$,
    20,
    $profile$Works at the intersection of yoga, subtle energetics, somatic practice and craniosacral work.$profile$,
    $profile$Cat Kabira is a long-standing yoga teacher, energy practitioner and educator working at the intersection of yoga, subtle energetics, somatic practice and craniosacral work. She has taught internationally for more than two decades and developed practitioner and teacher trainings through Yoga Energetics and the Kabira Energy School.$profile$,
    array[$profile$20+ years' professional experience$profile$, $profile$Founder, Yoga Energetics YTT / Kabira Energy School$profile$],
    null, true, true, $profile$https://www.catkabira.com/$profile$, $profile$https://www.instagram.com/catkabira/$profile$, null, null, 'draft', null
  ),
  (
    '00000000-0000-0000-0000-000000001014',
    'robyn-narciso',
    $profile$Robyn Narciso$profile$,
    $profile$Women’s Hormone Health · Functional Nutrition · Perimenopause$profile$,
    8,
    $profile$Supports women through hormone, metabolic and midlife change with a practical, whole-person approach.$profile$,
    $profile$Robyn Narciso specialises in women’s hormone health, with a particular focus on perimenopause, metabolic and thyroid patterns, gut health and sustainable lifestyle change. Her current work combines women’s hormone education, functional nutrition and practical wellbeing support, informed by a broader background in yoga, Medical QiGong and Ayurveda.$profile$,
    array[$profile$Women’s hormone health practitioner$profile$, $profile$Training through MindBody Institute Australia and Kresser Institute$profile$],
    null, true, true, $profile$https://thenaturalmindbody.com/$profile$, $profile$https://www.instagram.com/thenaturalmindbody/$profile$, null, null, 'draft', null
  ),
  (
    '00000000-0000-0000-0000-000000001015',
    'ida-resi-alit',
    $profile$Ida Resi Alit$profile$,
    $profile$Balinese Hindu High Priestess · Meditation · Melukat$profile$,
    null,
    $profile$A Balinese Hindu High Priestess sharing traditional practices of meditation, prayer, water purification and spiritual connection.$profile$,
    $profile$Ida Resi Alit is a Balinese Hindu High Priestess (Sulinggih) from Bangli. Her work is rooted in Balinese Hindu spiritual practice and includes meditation, prayer, mantra and Melukat water purification. She was first ordained in 2007 at the age of 21. After relinquishing her Sulinggih status on marriage in 2018, she underwent Mediksa again in 2024; PHDI Bangli publicly confirmed that the process had been handled according to the applicable religious rules. She welcomes people from Bali and around the world for spiritual practice, ceremony and reflection.$profile$,
    array[$profile$Balinese Hindu High Priestess (Sulinggih)$profile$, $profile$First ordained in 2007$profile$, $profile$Sulinggih status restored through Mediksa in 2024, corroborated by PHDI Bangli reporting$profile$],
    null, true, true, $profile$https://idaresialit.org/$profile$, $profile$https://www.instagram.com/idaresialit/?hl=en$profile$, null, null, 'draft', null
  ),
  (
    '00000000-0000-0000-0000-000000001016',
    'sook-fun-chen',
    $profile$Sook Fun Chen$profile$,
    $profile$Pilates · GYROTONIC® · Rolfing® · Functional Anatomy$profile$,
    25,
    $profile$Combines movement, anatomy and bodywork to support rehabilitation, alignment, strength and pain-free movement.$profile$,
    $profile$Sook Fun Chen is the founder of Movement Matters Bali and a movement and bodywork practitioner with more than 25 years in physical fitness and wellbeing. Her work combines Pilates, GYROTONIC®, Rolfing® Structural Integration, functional anatomy and post-rehabilitation movement, and she also trains movement professionals.$profile$,
    array[$profile$Certified Rolfer™$profile$, $profile$Certified Rolf Movement® Practitioner$profile$, $profile$GYROTONIC® trainer$profile$, $profile$Founder, Movement Matters Bali$profile$],
    null, true, true, $profile$https://movementmatters-bali.com/$profile$, $profile$https://www.instagram.com/sookfunchen/$profile$, null, null, 'draft', null
  ),
  (
    '00000000-0000-0000-0000-000000001017',
    'rachel-ellery',
    $profile$Rachel Ellery$profile$,
    $profile$Osteopathy · Functional Anatomy · Pilates Rehabilitation$profile$,
    26,
    $profile$A UK-trained osteopath and anatomy educator bringing together hands-on bodywork, rehabilitation and movement education.$profile$,
    $profile$Rachel Ellery is a UK-trained osteopath, Pilates rehabilitation instructor and internationally recognised anatomy educator. She combines more than 26 years of hands-on experience with extensive teaching in functional anatomy, movement and bodywork, working with yoga students, teachers, movement professionals and private clients.$profile$,
    array[$profile$British School of Osteopathy graduate (2000)$profile$, $profile$New Zealand-trained Pilates rehabilitation instructor$profile$, $profile$26+ years hands-on practice$profile$, $profile$17+ years functional anatomy teaching$profile$],
    null, true, true, $profile$https://www.theanatomyschool.com/$profile$, $profile$https://www.instagram.com/theanatomyschool/$profile$, null, null, 'draft', null
  ),
  (
    '00000000-0000-0000-0000-000000001018',
    'aaron-binning',
    $profile$Aaron Binning$profile$,
    $profile$Young Men’s Mentorship · Rites of Passage · Youth Development$profile$,
    null,
    $profile$Mentors boys and young men through challenge, reflection, community and meaningful rites-of-passage experiences.$profile$,
    $profile$Aaron Binning is the founder and lead mentor of The Road, a Bali-based initiative supporting boys and young men through mentorship, group experiences, challenge and rites of passage. Before founding The Road, he spent five years as a social work and youth education working with at-risk youth. His approach is grounded in lived experience, conversation, responsibility, nature and healthy male community.$profile$,
    array[$profile$Founder & Lead Mentor, The Road$profile$, $profile$Five years working in social work and youth education with at-risk youth$profile$],
    null, true, true, $profile$https://theroadbali.com/$profile$, $profile$https://www.instagram.com/theroadbali/$profile$, null, null, 'draft', null
  ),
  (
    '00000000-0000-0000-0000-000000001019',
    'livy-von-goh',
    $profile$Livy Von Goh$profile$,
    $profile$Sleep & Dream Wellness · Dreamwork$profile$,
    null,
    $profile$Explores restorative sleep and dream practice through private sessions, workshops, retreats and guided experiences.$profile$,
    $profile$Livy Von Goh is a sleep and dream guide working across restorative rest, sleep wellbeing and dream exploration. Her work includes private sessions, guided practices, workshops and retreats, creating practical and reflective ways for people to improve their relationship with sleep, rest and dreaming.$profile$,
    array[$profile$Sleep & Dream Guide / facilitator$profile$, $profile$Private sessions, workshops and retreats$profile$],
    null, true, true, $profile$https://livyvongoh.space/$profile$, $profile$https://www.instagram.com/livyvongoh/$profile$, null, null, 'draft', null
  ),
  (
    '00000000-0000-0000-0000-000000001020',
    'kerry-clancey',
    $profile$Kerry Clancey$profile$,
    $profile$Craniosacral · Energy Healing · Spiritual Coaching$profile$,
    null,
    $profile$Works across craniosacral therapy, Reiki, sound, meditation and spiritual coaching in an integrative healing practice.$profile$,
    $profile$Kerry Clancey is a spiritual teacher and integrative healing practitioner whose public work spans craniosacral therapy, Reiki, sound healing, meditation, spiritual and life coaching, crystal work and Ayurveda. Her practice brings together body-based and energetic approaches with contemplative and spiritual guidance.$profile$,
    array[$profile$Long-standing practitioner in craniosacral, energy, sound and spiritual wellbeing work$profile$],
    null, true, true, $profile$https://kerrythehealer.com/$profile$, $profile$https://www.instagram.com/kerrythehealer/$profile$, null, null, 'draft', null
  )
on conflict (id) do nothing;

-- Link each supplied profile to its ordered, profile-sourced terms. The
-- explicit arrays keep this seed readable while preserving source order.
with profile_terms (slug, term_type, term_names) as (
  values
    ('kartika-alexandra', 'support_area', array[$term$Trauma & nervous system$term$, $term$Anxiety & emotional wellbeing$term$, $term$Stress & burnout$term$, $term$Life transitions$term$, $term$Leadership & work$term$, $term$Relationships & intimacy$term$]::text[]),
    ('kartika-alexandra', 'approach', array[$term$Therapy & counselling$term$, $term$Somatic & body-based$term$]::text[]),
    ('kartika-alexandra', 'modality', array[$term$Integrative hypnotherapy$term$, $term$Subconscious pattern work$term$, $term$Trauma-informed practice$term$]::text[]),
    ('kartika-alexandra', 'works_with', array[$term$Individuals$term$, $term$Leaders & professional teams$term$]::text[]),
    ('kartika-alexandra', 'location', array[$term$Bali$term$]::text[]),
    ('kartika-alexandra', 'language', array[$term$English$term$]::text[]),

    ('sandra-echemendia', 'support_area', array[$term$Leadership & work$term$, $term$Stress & burnout$term$, $term$Life transitions$term$, $term$Purpose & personal growth$term$]::text[]),
    ('sandra-echemendia', 'approach', array[$term$Coaching$term$]::text[]),
    ('sandra-echemendia', 'modality', array[$term$Strategy advisory$term$, $term$Mentoring$term$, $term$Leadership and organisational transformation$term$, $term$NLP-informed work$term$]::text[]),
    ('sandra-echemendia', 'works_with', array[$term$Individuals$term$, $term$Leaders & professional teams$term$]::text[]),
    ('sandra-echemendia', 'location', array[$term$Bali$term$, $term$International$term$]::text[]),
    ('sandra-echemendia', 'language', array[$term$English$term$]::text[]),

    ('helena-day', 'support_area', array[$term$Leadership & work$term$, $term$Stress & burnout$term$, $term$Anxiety & emotional wellbeing$term$, $term$Life transitions$term$, $term$Purpose & personal growth$term$]::text[]),
    ('helena-day', 'approach', array[$term$Coaching$term$, $term$Therapy & counselling$term$, $term$Somatic & body-based$term$]::text[]),
    ('helena-day', 'modality', array[$term$Subconscious mastery coaching$term$, $term$Hypnotherapy / RTT$term$, $term$Narrative Coaching$term$, $term$Conversational Intelligence$term$, $term$Somatics & embodiment$term$]::text[]),
    ('helena-day', 'works_with', array[$term$Individuals$term$, $term$Leaders & professional teams$term$]::text[]),
    ('helena-day', 'location', array[$term$Bali$term$, $term$International$term$]::text[]),
    ('helena-day', 'language', array[$term$English$term$]::text[]),

    ('punnu-singh-wasu', 'support_area', array[$term$Stress & burnout$term$, $term$Purpose & personal growth$term$, $term$Anxiety & emotional wellbeing$term$]::text[]),
    ('punnu-singh-wasu', 'approach', array[$term$Meditation & mindfulness$term$, $term$Energy & sound$term$, $term$Traditional & spiritual practices$term$]::text[]),
    ('punnu-singh-wasu', 'modality', array[$term$Usui Reiki$term$, $term$Karuna Reiki$term$, $term$Kirtan$term$, $term$Meditation$term$, $term$Sound healing$term$, $term$Shiatsu Anma$term$, $term$Pranic healing$term$, $term$Crystal therapy$term$, $term$Chakra work$term$]::text[]),
    ('punnu-singh-wasu', 'works_with', array[$term$Individuals$term$, $term$Groups$term$]::text[]),
    ('punnu-singh-wasu', 'location', array[$term$Bali$term$, $term$Switzerland$term$, $term$International$term$]::text[]),
    ('punnu-singh-wasu', 'language', array[$term$English$term$]::text[]),

    ('kimberley-utama', 'support_area', array[$term$Stress & burnout$term$, $term$Purpose & personal growth$term$, $term$Physical wellbeing$term$]::text[]),
    ('kimberley-utama', 'approach', array[$term$Yoga & movement$term$, $term$Meditation & mindfulness$term$, $term$Coaching$term$]::text[]),
    ('kimberley-utama', 'modality', array[$term$Vinyasa Yoga$term$, $term$Restorative Yoga$term$, $term$Meditation$term$, $term$Pranayama$term$, $term$Trauma-Informed Yoga$term$, $term$Reiki$term$, $term$Teacher mentoring$term$]::text[]),
    ('kimberley-utama', 'works_with', array[$term$Individuals$term$, $term$Groups$term$]::text[]),
    ('kimberley-utama', 'location', array[$term$Bali$term$]::text[]),
    ('kimberley-utama', 'language', array[$term$English$term$]::text[]),

    ('beta-gaiana-lisboa', 'support_area', array[$term$Trauma & nervous system$term$, $term$Stress & burnout$term$, $term$Anxiety & emotional wellbeing$term$, $term$Women’s wellbeing$term$, $term$Physical wellbeing$term$]::text[]),
    ('beta-gaiana-lisboa', 'approach', array[$term$Somatic & body-based$term$, $term$Breathwork$term$, $term$Yoga & movement$term$, $term$Bodywork & physical therapies$term$]::text[]),
    ('beta-gaiana-lisboa', 'modality', array[$term$Somatic trauma work$term$, $term$Somatic Trauma Release Breathwork$term$, $term$Biodynamic Trauma Release Breathwork$term$, $term$Myofascial Release$term$, $term$Dynamic Spiral Yin Fascial Yoga$term$, $term$Family Constellation$term$]::text[]),
    ('beta-gaiana-lisboa', 'works_with', array[$term$Individuals$term$, $term$Groups$term$]::text[]),
    ('beta-gaiana-lisboa', 'location', array[$term$Bali$term$, $term$International$term$]::text[]),
    ('beta-gaiana-lisboa', 'language', array[$term$English$term$]::text[]),

    ('clare-hampton', 'support_area', array[$term$Anxiety & emotional wellbeing$term$, $term$Stress & burnout$term$, $term$Purpose & personal growth$term$, $term$Life transitions$term$]::text[]),
    ('clare-hampton', 'approach', array[$term$Therapy & counselling$term$, $term$Energy & sound$term$]::text[]),
    ('clare-hampton', 'modality', array[$term$Holistic Hypnotherapy$term$, $term$Usui Reiki$term$]::text[]),
    ('clare-hampton', 'works_with', array[$term$Individuals$term$]::text[]),
    ('clare-hampton', 'location', array[$term$Bali$term$]::text[]),
    ('clare-hampton', 'language', array[$term$English$term$]::text[]),

    ('dirk-hamelijnck', 'support_area', array[$term$Stress & burnout$term$, $term$Trauma & nervous system$term$, $term$Physical wellbeing$term$, $term$Anxiety & emotional wellbeing$term$]::text[]),
    ('dirk-hamelijnck', 'approach', array[$term$Breathwork$term$, $term$Somatic & body-based$term$]::text[]),
    ('dirk-hamelijnck', 'modality', array[$term$Breathwork$term$, $term$Cold exposure$term$, $term$TRE$term$, $term$Body-oriented practice$term$, $term$Systemic work$term$]::text[]),
    ('dirk-hamelijnck', 'works_with', array[$term$Individuals$term$, $term$Groups$term$]::text[]),
    ('dirk-hamelijnck', 'location', array[$term$Bali$term$, $term$Netherlands$term$]::text[]),
    ('dirk-hamelijnck', 'language', array[$term$English$term$]::text[]),

    ('indri-hapsari', 'support_area', array[$term$Stress & burnout$term$, $term$Anxiety & emotional wellbeing$term$, $term$Trauma & nervous system$term$, $term$Life transitions$term$, $term$Women’s wellbeing$term$]::text[]),
    ('indri-hapsari', 'approach', array[$term$Breathwork$term$, $term$Somatic & body-based$term$, $term$Energy & sound$term$, $term$Yoga & movement$term$]::text[]),
    ('indri-hapsari', 'modality', array[$term$Breathwork$term$, $term$Reiki$term$, $term$Prenatal Yoga$term$, $term$Aquatic bodywork$term$, $term$Hypnotherapy$term$]::text[]),
    ('indri-hapsari', 'works_with', array[$term$Individuals$term$, $term$Groups$term$]::text[]),
    ('indri-hapsari', 'location', array[$term$Bali$term$]::text[]),
    ('indri-hapsari', 'language', array[$term$English$term$]::text[]),

    ('rajiv-arapurakal', 'support_area', array[$term$Leadership & work$term$, $term$Physical wellbeing$term$, $term$Purpose & personal growth$term$, $term$Life transitions$term$, $term$Stress & burnout$term$]::text[]),
    ('rajiv-arapurakal', 'approach', array[$term$Yoga & movement$term$, $term$Coaching$term$, $term$Meditation & mindfulness$term$]::text[]),
    ('rajiv-arapurakal', 'modality', array[$term$ISHTA Yoga$term$, $term$Yin Yoga$term$, $term$Integrative wellbeing$term$, $term$Chakra work$term$, $term$Longevity$term$]::text[]),
    ('rajiv-arapurakal', 'works_with', array[$term$Individuals$term$, $term$Leaders & professional teams$term$, $term$Groups$term$]::text[]),
    ('rajiv-arapurakal', 'location', array[$term$Bali$term$, $term$International$term$]::text[]),
    ('rajiv-arapurakal', 'language', array[$term$English$term$]::text[]),

    ('claudia-pietrantoni', 'support_area', array[$term$Relationships & intimacy$term$, $term$Anxiety & emotional wellbeing$term$, $term$Life transitions$term$, $term$Grief & loss$term$, $term$Leadership & work$term$, $term$Purpose & personal growth$term$]::text[]),
    ('claudia-pietrantoni', 'approach', array[$term$Therapy & counselling$term$, $term$Coaching$term$]::text[]),
    ('claudia-pietrantoni', 'modality', array[$term$Humanistic Gestalt Counselling$term$, $term$Integrated counselling$term$, $term$Humanistic coaching$term$]::text[]),
    ('claudia-pietrantoni', 'works_with', array[$term$Individuals$term$, $term$Couples$term$, $term$Children & teenagers$term$, $term$Leaders & professional teams$term$]::text[]),
    ('claudia-pietrantoni', 'location', array[$term$Bali$term$, $term$Italy$term$]::text[]),
    ('claudia-pietrantoni', 'language', array[$term$English$term$]::text[]),

    ('alexandre-tsuk', 'support_area', array[$term$Stress & burnout$term$, $term$Physical wellbeing$term$, $term$Anxiety & emotional wellbeing$term$, $term$Purpose & personal growth$term$]::text[]),
    ('alexandre-tsuk', 'approach', array[$term$Breathwork$term$, $term$Somatic & body-based$term$]::text[]),
    ('alexandre-tsuk', 'modality', array[$term$Breathing Cold method$term$, $term$Breathwork$term$, $term$Cold exposure$term$, $term$Ice bath facilitation$term$]::text[]),
    ('alexandre-tsuk', 'works_with', array[$term$Individuals$term$, $term$Groups$term$]::text[]),
    ('alexandre-tsuk', 'location', array[$term$Bali$term$, $term$International$term$]::text[]),
    ('alexandre-tsuk', 'language', array[$term$English$term$]::text[]),

    ('cat-kabira', 'support_area', array[$term$Trauma & nervous system$term$, $term$Purpose & personal growth$term$, $term$Stress & burnout$term$, $term$Physical wellbeing$term$]::text[]),
    ('cat-kabira', 'approach', array[$term$Yoga & movement$term$, $term$Somatic & body-based$term$, $term$Energy & sound$term$, $term$Traditional & spiritual practices$term$]::text[]),
    ('cat-kabira', 'modality', array[$term$Yoga Energetics$term$, $term$Craniosacral work$term$, $term$Energy healing$term$, $term$Somatic practice$term$, $term$Shamanic / spiritual traditions$term$]::text[]),
    ('cat-kabira', 'works_with', array[$term$Individuals$term$, $term$Groups$term$]::text[]),
    ('cat-kabira', 'location', array[$term$Bali$term$, $term$International$term$]::text[]),
    ('cat-kabira', 'language', array[$term$English$term$]::text[]),

    ('robyn-narciso', 'support_area', array[$term$Women’s wellbeing$term$, $term$Physical wellbeing$term$, $term$Life transitions$term$, $term$Stress & burnout$term$]::text[]),
    ('robyn-narciso', 'approach', array[$term$Nutrition & lifestyle$term$, $term$Coaching$term$]::text[]),
    ('robyn-narciso', 'modality', array[$term$Women’s hormone health$term$, $term$Functional nutrition$term$, $term$Perimenopause support$term$, $term$Lifestyle coaching$term$]::text[]),
    ('robyn-narciso', 'works_with', array[$term$Individuals$term$]::text[]),
    ('robyn-narciso', 'location', array[$term$Bali$term$, $term$International$term$]::text[]),
    ('robyn-narciso', 'language', array[$term$English$term$]::text[]),

    ('ida-resi-alit', 'support_area', array[$term$Spiritual practice & connection$term$, $term$Life transitions$term$, $term$Emotional wellbeing$term$, $term$Purpose & personal growth$term$]::text[]),
    ('ida-resi-alit', 'approach', array[$term$Traditional & spiritual practices$term$, $term$Meditation & mindfulness$term$]::text[]),
    ('ida-resi-alit', 'modality', array[$term$Melukat / Balinese water purification$term$, $term$Meditation$term$, $term$Prayer$term$, $term$Mantra$term$, $term$Balinese Hindu spiritual practice$term$]::text[]),
    ('ida-resi-alit', 'works_with', array[$term$Individuals$term$, $term$Groups$term$]::text[]),
    ('ida-resi-alit', 'location', array[$term$Bali$term$, $term$International$term$]::text[]),
    ('ida-resi-alit', 'language', array[$term$English$term$]::text[]),

    ('sook-fun-chen', 'support_area', array[$term$Physical wellbeing$term$, $term$Stress & burnout$term$]::text[]),
    ('sook-fun-chen', 'approach', array[$term$Bodywork & physical therapies$term$, $term$Yoga & movement$term$]::text[]),
    ('sook-fun-chen', 'modality', array[$term$Pilates$term$, $term$GYROTONIC®$term$, $term$Rolfing® Structural Integration$term$, $term$Functional anatomy$term$, $term$Post-rehabilitation movement$term$]::text[]),
    ('sook-fun-chen', 'works_with', array[$term$Individuals$term$, $term$Groups$term$]::text[]),
    ('sook-fun-chen', 'location', array[$term$Bali$term$, $term$International$term$]::text[]),
    ('sook-fun-chen', 'language', array[$term$English$term$]::text[]),

    ('rachel-ellery', 'support_area', array[$term$Physical wellbeing$term$, $term$Stress & burnout$term$]::text[]),
    ('rachel-ellery', 'approach', array[$term$Bodywork & physical therapies$term$, $term$Yoga & movement$term$]::text[]),
    ('rachel-ellery', 'modality', array[$term$Osteopathy$term$, $term$Pilates rehabilitation$term$, $term$Functional anatomy$term$, $term$Craniosacral Osteopathy$term$, $term$Dry needling$term$, $term$Garuda$term$, $term$Zen Thai Shiatsu$term$]::text[]),
    ('rachel-ellery', 'works_with', array[$term$Individuals$term$, $term$Groups$term$]::text[]),
    ('rachel-ellery', 'location', array[$term$Bali$term$, $term$International$term$]::text[]),
    ('rachel-ellery', 'language', array[$term$English$term$]::text[]),

    ('aaron-binning', 'support_area', array[$term$Men’s wellbeing$term$, $term$Family & parenting$term$, $term$Purpose & personal growth$term$, $term$Anxiety & emotional wellbeing$term$]::text[]),
    ('aaron-binning', 'approach', array[$term$Coaching$term$, $term$Experiential / developmental$term$]::text[]),
    ('aaron-binning', 'modality', array[$term$Young men’s mentorship$term$, $term$Rites of passage$term$, $term$Youth development$term$, $term$Group facilitation$term$, $term$Outdoor challenge$term$]::text[]),
    ('aaron-binning', 'works_with', array[$term$Children & teenagers$term$, $term$Individuals$term$, $term$Groups$term$]::text[]),
    ('aaron-binning', 'location', array[$term$Bali$term$]::text[]),
    ('aaron-binning', 'language', array[$term$English$term$]::text[]),

    ('livy-von-goh', 'support_area', array[$term$Sleep & rest$term$, $term$Stress & burnout$term$, $term$Anxiety & emotional wellbeing$term$, $term$Purpose & personal growth$term$, $term$Leadership & work$term$]::text[]),
    ('livy-von-goh', 'approach', array[$term$Meditation & mindfulness$term$, $term$Coaching / guided practice$term$, $term$Sleep & dreamwork$term$]::text[]),
    ('livy-von-goh', 'modality', array[$term$Sleep wellness$term$, $term$Dreamwork$term$, $term$Conscious dreaming$term$, $term$Guided meditation$term$, $term$Sleep and dream workshops$term$]::text[]),
    ('livy-von-goh', 'works_with', array[$term$Individuals$term$, $term$Groups$term$, $term$Leaders & professional teams$term$]::text[]),
    ('livy-von-goh', 'location', array[$term$Indonesia$term$, $term$Singapore$term$, $term$Portugal$term$, $term$Kenya$term$, $term$UK$term$]::text[]),
    ('livy-von-goh', 'language', array[$term$English$term$]::text[]),

    ('kerry-clancey', 'support_area', array[$term$Purpose & personal growth$term$, $term$Anxiety & emotional wellbeing$term$, $term$Stress & burnout$term$, $term$Life transitions$term$]::text[]),
    ('kerry-clancey', 'approach', array[$term$Energy & sound$term$, $term$Traditional & spiritual practices$term$, $term$Somatic & body-based$term$, $term$Coaching$term$]::text[]),
    ('kerry-clancey', 'modality', array[$term$Craniosacral therapy$term$, $term$Reiki$term$, $term$Sound healing$term$, $term$Meditation$term$, $term$Spiritual coaching$term$, $term$Crystal therapy$term$, $term$Ayurveda$term$]::text[]),
    ('kerry-clancey', 'works_with', array[$term$Individuals$term$, $term$Groups$term$]::text[]),
    ('kerry-clancey', 'location', array[$term$Bali$term$, $term$International$term$]::text[]),
    ('kerry-clancey', 'language', array[$term$English$term$]::text[])
), expanded as (
  select pt.slug, pt.term_type, u.term_name, u.display_order
    from profile_terms as pt
    cross join lateral unnest(pt.term_names) with ordinality as u(term_name, display_order)
)
insert into public.practitioner_term_links (practitioner_id, term_id, display_order)
select p.id, t.id, e.display_order - 1
  from expanded as e
  join public.practitioners as p on p.slug = e.slug
  join public.practitioner_terms as t on t.type = e.term_type and t.name = e.term_name
on conflict (practitioner_id, term_id) do nothing;

insert into public.practitioner_expressions_of_interest (
  id,
  full_name,
  email,
  contact_preference,
  practice_name,
  location,
  website_url,
  consent_confirmed,
  consent_given_at,
  questionnaire_answers,
  source,
  status,
  created_at,
  updated_at
)
values (
  '00000000-0000-0000-0000-000000000002',
  'Local Test Practitioner',
  'practitioner@example.test',
  'email',
  'Example Practice',
  'Example location',
  'https://example.test/practice',
  true,
  '2026-01-01T00:00:00Z',
  '{"modalities":["meditation"],"experience":"Synthetic local application","scope":"Example scope"}'::jsonb,
  'website',
  'new',
  '2026-01-01T00:00:00Z',
  '2026-01-01T00:00:00Z'
)
on conflict (id) do nothing;
