#!/usr/bin/env bash
# Per-boot startup: bring up Docker, the local Supabase stack, and ensure the
# local environment file exists. Runs on every environment start.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

echo "==> Starting Docker daemon"
"$REPO_ROOT/.cursor/start-docker.sh"

echo "==> Starting local Supabase stack"
# Idempotent: a no-op if the stack is already running.
supabase start

echo "==> Ensuring .env.local"
if [ ! -f .env.local ]; then
  # Export the local stack's connection details (keys are the standard,
  # non-secret local development values).
  eval "$(supabase status -o env 2>/dev/null | grep -E '^[A-Z0-9_]+=')"
  cat > .env.local <<EOF
# Generated by .cursor/start.sh for local development.
NEXT_PUBLIC_SUPABASE_URL=${API_URL}
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=${PUBLISHABLE_KEY}
# Server-side only; required by privileged paths such as enquiry submission.
SUPABASE_SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}
# MailerSend stays in a safe dev mode: a placeholder key means no real email
# delivery is attempted locally.
MAILERSEND_API_KEY=dev-placeholder-not-a-real-key
MAILERSEND_FROM_EMAIL=sender@example.com
MAILERSEND_FROM_NAME=The Solas Guide
SOLAS_OPERATIONS_EMAIL=operations@example.com
CRON_SECRET=local-dev-cron-secret-please-rotate-in-real-envs
NEXT_PUBLIC_APP_URL=http://localhost:3000
EOF
  echo ".env.local created."
else
  echo ".env.local already present; leaving it untouched."
fi

echo "==> start.sh complete"
